### PR TITLE
[MCC-143057] (no more) nested params

### PR DESCRIPTION
**Pull request by csavage-mdsol**
Per discussion, removing the nested params for create and update, which will eventually be covered by a bulk create. @sheavalentine-mdsol, @jlo188 heads up

```
Finished in 1 minute 6.6 seconds (files took 0.39836 seconds to load)
23 examples, 0 failures

Randomized with seed 23481
```

### CODE REVIEW

**Comment by sheavalentine-mdsol** [comment]
What media_type are you posting with?
url_encoded or json or both?

**Comment by csavage-mdsol** [comment]
Faraday uses url encoded by default.  Handing it json would just test the rails params parser wouldn't it?

**Comment by sheavalentine-mdsol** [comment]
Cool.  So, url it is.

Can we merge this?  If so I'll integrate it into Farscape right now, and my PR won't have a bunch of commented tests.

**Comment by csavage-mdsol** [comment]
It is ready, the change is pretty minimal

**Comment by sheavalentine-mdsol** [comment]
I'm merging

**Pull request merged**
